# 基本

## 一个简单的服务器示例

```js
const http = require('http');
http.createServer((request, response) => {
 response.writeHead(200, {"Content-Type": "text/plain"});
 response.write('hello world');
 response.end();
}).listen(80);
```

- 当这个服务器收到请求时，http.createServer 的匿名函数就会被调用。

- 当使用这个服务器访问网页时，该匿名函数会执行两次。因为还会默认访问 http://localhost:80/favicon.ico。可以使用 if(request.url === '/favicon.ico’) 来判断。

- 后端响应前端的请求返回一些数据给前端时，需要配置响应头的 Content-Type ,以便于前端正确的解析响应的数据。当返回普通类型的文本时，需要配置 `Content-Type: text/plain`。当返回html文档格式的内容时，需要配置 `Content-Type: text/html`。

- 全局环境中，this会返回顶层对象。但是，Node 模块和 ES6 模块中，this返回的是当前模块。

## Node 的捕获错误

### try...catch

使用 `try...catch` 无法捕获异步运行的代码抛出的异常，因为当异步代码出错时 catch 部分已经执行完毕了，可以把 catch 代码放到异步代码中。

### 回调函数

Node采用的方法，是将错误对象作为第一个参数，传入回调函数。这样就避免了捕获代码与发生错误的代码不在同一个时间段的问题。

### EventEmitter接口的error事件

发生错误的时候，使用用 EventEmitter 接口抛出 error 事件。

```js
var EventEmitter = require('events').EventEmitter;
var emitter = new EventEmitter();
emitter.emit('error', new Error('something bad happened'));

// 如果没有对error事件部署监听函数，会导致整个应用程序崩溃。所以必须同时部署监听代码
emitter.on('error', function(err) {
  console.error('出错：' + err.message);
});
```

### uncaughtException事件

当一个异常未被捕获，就会触发uncaughtException事件，可以对这个事件注册回调函数，从而捕获异常。只要给uncaughtException配置了回调，Node进程不会异常退出，但异常发生的上下文已经丢失，无法给出异常发生的详细信息。而且，异常可能导致Node不能正常进行内存回收，出现内存泄露。所以，当uncaughtException触发后，最好记录错误日志，然后结束Node进程。

```js
var logger = require('tracer').console();

process.on('uncaughtException', function(err) {
  logger.log(err); // 用来记录错误日志
  process.exit(1); // 结束Node进程
});
```

### unhandledRejection事件

使用unhandledRejection事件，用来监听没有捕获的Promise对象的rejected状态。unhandledRejection事件的监听函数有两个参数，第一个是错误对象，第二个是产生错误的promise对象。

```js
process.on('unhandledRejection', function (err, p) {
  console.error(err.stack);
})
```


## 一些 Node 命令

- cwd
  - `process.cwd()` 得到的是执行当前 node 命令时候的目录。
  - `__dirname` 得到的是被执行的 JS 文件的所在目录。
  - 比如对于 `d:\dir\index.js` 这个文件，执行 `node dir\index.js` 时，`process.cwd()` 得到的是 `d:`，`__dirname` 得到的是 `d:\dir`。
